### ISSUE TITLE
FlowItemAppearingCommand fires for items not visible

### ISSUE THREAD

**Issue by ozzy1873** [daniel-luberda/DLToolkit.Forms.Controls#77] opened 2017-03-05 01:09 UTC
FlvItemAppearingCommand seems to get executed even if the item is not actually in view. If I add enough items to the FlowListView such that the last item is below the bottom of the control and not visible, the command will still be executed for that item. This is working correctly on Android, but not on UWP.

**Comment by daniel-luberda** [comment] 2017-08-13 16:06
The problem is how it's implemented in Xamarin Forms `ListView`. `FlowListView` is a derivative od `ListView` and the same issues apply to it. I cannot do anything about it, as it should be fixed in Xamarin.Forms first. Cheers.

**Closed by daniel-luberda** 2017-08-13 16:06 UTC
