### ISSUE TITLE
Grouping example corrupted in Android 7.1

### ISSUE THREAD

**Issue by pzs7602** [daniel-luberda/DLToolkit.Forms.Controls#108] opened 2017-06-27 07:35 UTC
When choosing grouping example in project, scroll the screen, the app is corrupted. My phone is Google Pixel running Android 7.1.2. The error is the same on other Android devices running Android 7.0+
The error message:
System.NullReferenceException
Object reference not set to an instance of an object

**Comment by daniel-luberda** [comment] 2017-08-13 13:06
Could you post full stack trace?

**Comment by daniel-luberda** [comment] 2017-09-06 15:09
Duplicate of https://github.com/daniel-luberda/DLToolkit.Forms.Controls/issues/65

**Closed by daniel-luberda** 2017-09-06 15:09 UTC
