### ISSUE TITLE
FlowListView - ContextActions for each item separately

### ISSUE THREAD

**Issue by bprochniak** [daniel-luberda/DLToolkit.Forms.Controls#45] opened 2016-11-17 09:12 UTC
In my app I use FlowListView component. It is rendering fine with custom cell:

              <flv:FlowListView.FlowColumnTemplate>
                <DataTemplate>
                  
                      <StackLayout Spacing="8" Orientation="Vertical" VerticalOptions="Center" HorizontalOptions="FillAndExpand" BackgroundColor="Transparent">
                        <StackLayout Spacing="10" Padding="5,7,8,7" Orientation="Horizontal" VerticalOptions="Center" HorizontalOptions="FillAndExpand" BackgroundColor="Transparent">
                          <controls:CircleImage Source="{ Binding ProfileImageUrl }" WidthRequest="56" HeightRequest="56"
                            HorizontalOptions="Center" VerticalOptions="Center" Aspect="AspectFill"/>
                          <StackLayout Spacing="0" VerticalOptions="FillAndExpand" HorizontalOptions="FillAndExpand" BackgroundColor="Transparent">
                            <Label Text="{ Binding ListName }" Style="{StaticResource listItemTitle}" />
                            <Label Text="{ Binding ListDescription }" Style="{StaticResource listItemDescription}" />
                          </StackLayout>                                        
                        
                        </StackLayout>
    
                      </StackLayout>
                  
                  
                </DataTemplate>
              </flv:FlowListView.FlowColumnTemplate>

But because of a memory leak issue from the ListView on UWP I need to use native cell:

    <flv:FlowListView.FlowColumnTemplate>
                <DataTemplate>              
                      <contentViews:NativeCell ListName="{Binding ListName}" ListDescription="{Binding ListDescription}" ProfileImageUrl="{Binding ProfileImageUrl}" />                            
                </DataTemplate>
              </flv:FlowListView.FlowColumnTemplate>

With the code above I get blank list. If I add StackLayout:

              <flv:FlowListView.FlowColumnTemplate>
                <DataTemplate>              
                      <StackLayout >
                      <contentViews:NativeCell ListName="{Binding ListName}" ListDescription="{Binding ListDescription}" ProfileImageUrl="{Binding ProfileImageUrl}" />
                      </StackLayout>
                </DataTemplate>
              </flv:FlowListView.FlowColumnTemplate>

I get the below error message:

Unable to cast object of type 'MyApp.Core.ContentViews.NativeCell' to type 'Xamarin.Forms.VisualElement'.

Is there any way to make FlowListView work with Native cell? I checked and a plain ListView works fine with my native cell.

And this is my NativeCell:

    public class NativeCell : ViewCell
    {
        public static readonly BindableProperty ListNameProperty =
          BindableProperty.Create("ListName", typeof(string), typeof(NativeCell), "");

        public string ListName
        {
            get { return (string)GetValue(ListNameProperty); }
            set { SetValue(ListNameProperty, value); }
        }

        public static readonly BindableProperty ListDescriptionProperty =
          BindableProperty.Create("ListDescription", typeof(string), typeof(NativeCell), "");

        public string ListDescription
        {
            get { return (string)GetValue(ListDescriptionProperty); }
            set { SetValue(ListDescriptionProperty, value); }
        }

        public static readonly BindableProperty ProfileImageUrlProperty =
          BindableProperty.Create("ProfileImageUrl", typeof(string), typeof(NativeCell), "");

        public string ProfileImageUrl
        {
            get { return (string)GetValue(ProfileImageUrlProperty); }
            set { SetValue(ProfileImageUrlProperty, value); }
        }
    }

**Comment by daniel-luberda** [comment] 2016-11-18 01:55
It's simple. `FlowListView` doesn't use `ViewCell` as a base, but a normal `View`. So just subclass `View` in your custom platform specific cells. That's all.

**Comment by daniel-luberda** [comment] 2017-01-05 13:32
@julyorange I could expose that, but the problem is ContextActions will be called for the entire row, not single item (items are implemented inside ListView's row). 

You could access all `ViewCell` properties easily by creating custom renderer for `FlowListViewInternalCell`. Did you try that?

**Comment by julyorange** [comment] 2017-01-09 13:21
@daniel-luberda Thank you for your answer and justification about entire row.
Indeed, a _ViewCellRenderer_ on _FlowListViewInternalCell_ enables me to access _ViewCell_ object, but this object always targets the entire row of base _ListView_ but not single items on "grid" _FlowListView_ .
I did not manage to see contextual menu appears by setting _ContextActions_ in my custom renderer. :(
Correct me if I am wrong but it seems that it's not possible to implement contextual actions on a single item when I am using _FlowListView_ as a grid ?

**Comment by daniel-luberda** [comment] 2017-01-09 13:30
@julyorange You're right, it's not implemented.

> but this object always targets the entire row of base ListView but not single items on "grid" FlowListView .

`FlowListView` inherits from `ListView`, which is based on native controls for displaying list views, they only do support context actions for a single row - that's the problem.

**Comment by daniel-luberda** [comment] 2017-12-16 17:46
I'll close this one as Xamarin.Forms.ListView doesn't support that.

**Closed by daniel-luberda** 2017-12-16 17:46 UTC
Labels: enhancement

**Comment by gurw** [comment] 2019-03-12 04:38
Hello , sir  I am Using Flow List View Nuget For all platforms But in This list view i not Found the Selected item  and the tapped item  Background color  change the depend on Delay time  please add the FlowSelectedItem Event and Background color change only Selected item its not depend on Delay time Its depend on  when the User Click next item Click then previous  selected item color to   reset  and selected item color to update
